import type { PoliticalViewpoint } from './types';

export const POLITICAL_VIEWPOINTS: PoliticalViewpoint[] = [
  { id: 'anarcho-communist', name: 'Anarcho-communist', description: 'A political philosophy that advocates for the abolition of the state, capitalism, wage labor, and private property in favor of common ownership of the means of production. It envisions a society based on voluntary associations, direct democracy, and mutual aid, where resources are distributed according to the principle "From each according to his ability, to each according to his need."' },
  { id: 'communist', name: 'Communist', description: 'A political and economic ideology based on the theories of Karl Marx, aiming for a society where all property is publicly owned and each person works and is paid according to their abilities and needs. It seeks to establish a classless, stateless society through the revolutionary overthrow of the capitalist system.' },
  { id: 'marxist-leninist', name: 'Marxist-Leninist', description: 'A communist ideology that was the official state ideology of the Soviet Union. It posits that a revolutionary vanguard party is necessary to lead the working class in a revolution to overthrow capitalism and establish a socialist state, which will then develop into a fully communist society. It emphasizes the concept of a dictatorship of the proletariat as a transitional phase.' },
  { id: 'democratic-socialist', name: 'Democratic Socialist', description: 'A political philosophy that advocates for a socialist economy in which the means of production are socially and collectively owned or controlled, alongside a democratic political system of government. They reject revolutionary methods and believe that socialist goals can and should be achieved through gradual reforms and democratic processes within a capitalist society.' },
  { id: 'social-democrat', name: 'Social Democrat', description: 'A political ideology that supports social justice and economic interventionism within the framework of a liberal democratic polity and a capitalist-oriented mixed economy. It advocates for a strong welfare state, extensive social safety nets, collective bargaining rights for workers, and regulation of the economy in the public interest to create a more equitable and solidaristic society.' },
  { id: 'progressive', name: 'Progressive', description: 'A political philosophy in support of social reform and progress. It is based on the idea that advancements in science, technology, economic development, and social organization are vital to the improvement of the human condition. Progressives often advocate for government action to address social inequalities, protect the environment, and regulate the market.' },
  { id: 'liberal', name: 'Liberal', description: 'A political and moral philosophy based on liberty, consent of the governed, and equality before the law. Liberals espouse a wide array of views depending on their understanding of these principles, but they generally support civil rights, democracy, secularism, gender and racial equality, internationalism, and a market economy with some level of government intervention.' },
  { id: 'social-liberal', name: 'Social Liberal', description: 'A political ideology that seeks to balance individual liberty and social justice. It endorses a market economy and the expansion of civil and political rights, but differs from classical liberalism in believing that the legitimate role of the government includes addressing economic and social issues such as poverty, health care, and education.' },
  { id: 'centrist', name: 'Centrist', description: 'A political outlook or position that involves acceptance or support of a balance of a degree of social equality and a degree of social hierarchy, while opposing political changes which would result in a significant shift of society strongly to either the left or the right. It prioritizes pragmatism and moderation over strict ideological adherence.' },
  { id: 'third-way', name: 'Third Way', description: 'A political position akin to centrism that attempts to reconcile right-wing and left-wing politics by advocating a synthesis of right-wing economic policies (like free markets) with left-wing social policies (like social justice and a welfare state). It emphasizes a balance between rights and responsibilities, and between individualism and community.' },
  { id: 'classical-liberal', name: 'Classical Liberal', description: 'A political ideology that advocates for civil liberties under the rule of law with an emphasis on economic freedom. It developed in the 19th century and is rooted in the belief that individuals are rational beings who should be free to pursue their own interests. It strongly supports laissez-faire capitalism, limited government, and individual property rights.' },
  { id: 'libertarian', name: 'Libertarian', description: 'A political philosophy that upholds liberty as a core principle. Libertarians seek to maximize autonomy and political freedom, emphasizing free association, freedom of choice, individualism, and voluntary association. They are skeptical of authority and state power and advocate for minimal government intervention in all aspects of life.' },
  { id: 'conservative', name: 'Conservative', description: 'A political and social philosophy that promotes retaining traditional social institutions. Adherents of conservatism often oppose modernism and seek a return to traditional values. It emphasizes stability, order, and continuity, often supporting institutions like organized religion, parliamentary government, and property rights as conducive to social order.' },
  { id: 'fiscal-conservative', name: 'Fiscal Conservative', description: 'A political-economic philosophy regarding fiscal policy and fiscal responsibility with a political ideology that advocates for low taxes, reduced government spending, and minimal government debt. They believe that a free market, without government interference, is the most effective way to promote economic growth.' },
  { id: 'social-conservative', name: 'Social Conservative', description: 'A political ideology that focuses on the preservation of traditional values and social mores. Social conservatives are often motivated by religious beliefs and advocate for policies that reflect their views on family, morality, and social order. They tend to oppose things like abortion, same-sex marriage, and secularism in the public sphere.' },
  { id: 'nationalist', name: 'Nationalist', description: 'An ideology that emphasizes loyalty, devotion, or allegiance to a nation and holds that such obligations outweigh other individual or group interests. It promotes the interests of a particular nation, especially with the aim of gaining and maintaining the nation\'s sovereignty over its homeland. It often involves a sense of national consciousness and pride in one\'s culture and history.' },
  { id: 'populist-right', name: 'Populist Right', description: 'A political ideology which combines right-wing politics with populist rhetoric and themes. The rhetoric often consists of anti-elitist sentiments, opposition to the Establishment, and speaking for the "common people." It often includes nationalism, strong anti-immigration stances, and skepticism towards international cooperation and globalization.' },
  { id: 'authoritarian', name: 'Authoritarian', description: 'A form of government characterized by the rejection of political plurality, the use of strong central power to preserve the political status quo, and reductions in the rule of law, separation of powers, and democratic voting. Political power is concentrated in the hands of a single leader or a small elite, not constitutionally accountable to the body of the people.' },
  { id: 'fascist', name: 'Fascist', description: 'A far-right, authoritarian, ultranationalist political ideology characterized by dictatorial power, forcible suppression of opposition, and strong regimentation of society and the economy. It promotes a single-party state and believes in a totalitarian system where the state has complete control over all aspects of life.' },
  { id: 'totalitarian', name: 'Totalitarian', description: 'A concept for a form of government or political system that prohibits opposition parties, restricts individual opposition to the state and its claims, and exercises an extremely high degree of control over public and private life. It is regarded as the most extreme and complete form of authoritarianism.' },
];
